# Generated by Django 2.2.4 on 2019-08-05 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paperboy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('experience', models.PositiveIntegerField(default=0)),
                ('earnings', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
